### ISSUE TITLE
Autoload problem

### ISSUE THREAD

**Issue by Nirvanatin** [rafaelgou/padl#10]
I am just a newbie PHP coder. Sorry, if I ask, but I don't understand how to use your class. When I run the generate key example I get the below error:
`Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\padl\examples\example-generatekey.php on line 158

Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\padl\examples\example-generatekey.php on line 158`
How to solve this problem? I would appreciate your help if you could explain how to use your class in very basic steps.

**Comment by reeperbahnause** [comment]
Did you use composer to get the application? 
Get to know composer. It will cross your php developer life pretty often. 
If you need help, let me know! 
Cheers Phillip

**Comment by rafaelgou** [comment]
Sure thing, @reeperbahnause. Composer is a dependency manager for PHP, a must. This tool uses composer to manage its dependencies and to be included in any project.

@JToward, take a look at https://getcomposer.org/doc/00-intro.md to understand how it works and to search packages available see https://packagist.org/ .
