### ISSUE TITLE
check local

### ISSUE THREAD

**Issue by reeperbahnause** [rafaelgou/padl#7]
Hi, 

I think there is an issue with the localhost check.

The current check 
```php
// check if local  
$local = $this->allowLocal && (in_array('127.0.0.1', $data['SERVER']['IP']) || $data['PATH']['SERVER_ADDR'] === '127.0.0.1' || $data['PATH']['HTTP_HOST'] === '127.0.0.1');  
if (!$local) {  
    $data['RESULT'] = 'ILLEGAL_LOCAL';  
}  
```

should be changed to

```php
// check if local
if(in_array('127.0.0.1', $data['SERVER']['IP']) || $data['PATH']['SERVER_ADDR'] === '127.0.0.1' || $data['PATH']['HTTP_HOST'] === '127.0.0.1'){
    if (!$this->allowLocal){
        $data['RESULT'] = 'ILLEGAL_LOCAL';
    }
}
```

Otherwise allowLocal has to be set to `true` and the ip `127.0.0.1` has to be in one of the server parameters.

Or am I missing something?

Cheers

**Comment by rafaelgou** [comment]
I believe I understand your point.

`ILLEGAL_LOCAL` will happen even if no local IP is sent when `$this->allowLocal` is false.

Could you send a pull request?

**Comment by reeperbahnause** [comment]
Correct. That's what i was thinking.
I just created my first pull request and hope it is how it is supposed to be ;-)
Thank for your work and all the best for the new year!
Cheers

**Comment by rafaelgou** [comment]
Thanks! And 2017 be the best for us!
